// <auto-generated />
using System;
using Core.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20240205203320_AddTablesAndModelSeedData")]
    partial class AddTablesAndModelSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Feria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ferie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("035463c9-2fe9-4302-9831-33e2f91fe86b"),
                            DataFine = new DateTime(2024, 1, 7, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Vacanza",
                            Durata = 7
                        },
                        new
                        {
                            Id = new Guid("c4f1d856-e2d9-4179-89c4-69a0766143bf"),
                            DataFine = new DateTime(2024, 1, 14, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Week-end",
                            Durata = 2
                        },
                        new
                        {
                            Id = new Guid("ea707300-a3ea-4727-b84b-2632a765226e"),
                            DataFine = new DateTime(2024, 1, 21, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Ferie",
                            Durata = 4
                        },
                        new
                        {
                            Id = new Guid("ed542edf-f36a-44ab-87f6-f835adf7fe85"),
                            DataFine = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Ferie",
                            Durata = 60
                        },
                        new
                        {
                            Id = new Guid("1cff505e-0e61-466b-b909-2aa7b2c52a59"),
                            DataFine = new DateTime(2024, 2, 4, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Ferie",
                            Durata = 4
                        });
                });

            modelBuilder.Entity("Core.Models.NotteFuori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViaggio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NottiFuori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fa4b603-cb2d-4abd-905b-85287d772a0b"),
                            Commessa = "Commessa di notte fuori",
                            Data = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di notte fuori",
                            TipoViaggio = "Lavoro"
                        },
                        new
                        {
                            Id = new Guid("c761763c-3c86-4e72-94bd-ad9939f8a88a"),
                            Commessa = "Riparazione",
                            Data = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Data la distanza tra l'azienda e cliente necessita di essere vicini per velocizzare la riparazione per il giorno dopo",
                            TipoViaggio = "Lavoro"
                        });
                });

            modelBuilder.Entity("Core.Models.Permesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permessi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3349d448-afeb-4910-a8d9-9056c672d7a6"),
                            Data = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Medica",
                            Durata = 120,
                            OraFine = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1083cffd-f10c-4694-8791-1189127e761b"),
                            Data = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di permesso",
                            Durata = 180,
                            OraFine = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f15cbbfe-22be-4e93-b89d-1226428d4922"),
                            Data = new DateTime(2024, 1, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Familiare",
                            Durata = 180,
                            OraFine = new DateTime(2024, 1, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 29, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("120c6305-502e-4c00-a191-b04e056db371"),
                            Data = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Malattia",
                            Durata = 240,
                            OraFine = new DateTime(2024, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4998f3e3-b706-404a-8cb8-f8651fd6a23b"),
                            Data = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Malattia",
                            Durata = 180,
                            OraFine = new DateTime(2024, 2, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("27f4e6d2-867a-4dd9-9272-5b5f4ef25211"),
                            Data = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Familiare",
                            Durata = 180,
                            OraFine = new DateTime(2024, 2, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Core.Models.Rendicontazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime2");

                    b.Property<int>("OreTotali")
                        .HasColumnType("int");

                    b.Property<bool>("Straordinario")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rendicontazioni");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62fda361-35df-48d1-a101-596e732b094b"),
                            Commessa = "Sistemazione",
                            Data = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Sistemato un problema del cliente",
                            OraFine = new DateTime(2024, 1, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("9b86d36d-1c39-455a-aad7-1f55b8719aab"),
                            Commessa = "Sistemazione",
                            Data = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Sistemato un problema del cliente",
                            OraFine = new DateTime(2024, 1, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("f6f13114-21aa-4333-a646-44d578ed4116"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto",
                            OraFine = new DateTime(2024, 1, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("c5ebe7dc-5629-41c6-803a-772d40ff67ad"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto",
                            OraFine = new DateTime(2024, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("de13d3bd-ed34-4593-ba4d-15a2ef212416"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("b58b2163-86bd-407b-b863-6b2e4c97c988"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("034bfb43-d9b9-4904-b947-17aa19955886"),
                            Commessa = "progetto",
                            Data = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Elaborazione del progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("68989d6b-ddcd-4ac2-b341-efcdcd535abf"),
                            Commessa = "progetto",
                            Data = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Elaborazione del progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("9282f878-81f8-4734-b3a3-84da8719ac85"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("bf824391-ff81-4185-b101-d7d8571fcb6f"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("c774480a-f7a1-48e1-9e75-455207e89e16"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Pianificazione del progetto",
                            OraFine = new DateTime(2024, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("d5842dab-7975-4d46-8495-df23279e79c9"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Pianificazione del progetto",
                            OraFine = new DateTime(2024, 1, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 3,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("a5f2d0cf-5ef3-4cef-8e5f-56c29a69b9f0"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("6aff4535-b290-427a-9b40-3b36c034f4c3"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("247ff325-479f-4d81-a826-8124e6fbd155"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 17, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 17, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 17, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 1,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("6b5b46e6-a48a-43b2-b0be-7adfbe083385"),
                            Commessa = "Commessa di rendicontazione",
                            Data = new DateTime(2024, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Rendicontazioni",
                            OraFine = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 2,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("549945c2-1e36-4884-b281-3a8459cd08bd"),
                            Commessa = "Commessa di rendicontazione",
                            Data = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Rendicontazioni",
                            OraFine = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 1,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("cd3816b4-45c7-42c2-8864-d5238c6f1c50"),
                            Commessa = "Commessa di rendicontazione",
                            Data = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Rendicontazioni",
                            OraFine = new DateTime(2024, 1, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 2,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("fa0c62fd-3a81-4bb2-a931-2ef684cf5db4"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 3,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("2043a196-e0e1-44cb-af46-ab6617fdbc2b"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 1, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro del progetto straordinario",
                            OraFine = new DateTime(2024, 1, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 3,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("707eceef-d9ec-4d2c-a082-946a6a848d0e"),
                            Commessa = "Aggiustamento",
                            Data = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Aggiustamento ad un problema del cliente",
                            OraFine = new DateTime(2024, 2, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("0cf695cb-1452-4c0d-897f-3530da0a8c5d"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Termine del progetto",
                            OraFine = new DateTime(2024, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("e8313311-2ded-4821-a7d3-b24f54da70b5"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        });
                });

            modelBuilder.Entity("Core.Models.Rimborso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CartaAziendale")
                        .HasColumnType("bit");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rimborsi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32c6a286-b822-4e54-b6f2-4fd5e90e9b82"),
                            CartaAziendale = false,
                            Commessa = "Commessa di rimborso",
                            Data = new DateTime(2024, 1, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Rimborso per il viaggio",
                            Importo = 100
                        },
                        new
                        {
                            Id = new Guid("c177bef6-cfe0-442f-9d04-41c8f7f8a105"),
                            CartaAziendale = false,
                            Commessa = "Commessa di rimborso",
                            Data = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di rimborso",
                            Importo = 100
                        },
                        new
                        {
                            Id = new Guid("e4729c5c-df86-4983-98cc-1a0dd9555640"),
                            CartaAziendale = true,
                            Commessa = "Riparazione",
                            Data = new DateTime(2024, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Rimborso per il viaggio",
                            Importo = 120
                        });
                });

            modelBuilder.Entity("Core.Models.Trasferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoAziendale")
                        .HasColumnType("bit");

                    b.Property<int>("Chilometri")
                        .HasColumnType("int");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trasferte");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef4e9192-c547-4ec4-bd2b-c8ad238edb60"),
                            AutoAziendale = false,
                            Chilometri = 200,
                            Commessa = "Aggiornamento",
                            DataFine = new DateTime(2024, 1, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 16, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Aggiornamento del sistema richiesto al cliente"
                        },
                        new
                        {
                            Id = new Guid("7657b97b-52e5-4d8b-b55b-a2c98ae25aad"),
                            AutoAziendale = false,
                            Chilometri = 200,
                            Commessa = "Commessa di Trasferte",
                            DataFine = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Trasferte"
                        },
                        new
                        {
                            Id = new Guid("9b6a3cec-bc36-4fd8-9201-cf17523a38a0"),
                            AutoAziendale = true,
                            Chilometri = 350,
                            Commessa = "Riparazione",
                            DataFine = new DateTime(2024, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Riparazione ad un guasto ad un macchinario del cliente"
                        });
                });

            modelBuilder.Entity("Core.Models.VueCalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AllDay")
                        .HasColumnType("bit");

                    b.Property<bool?>("Background")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Resizable")
                        .HasColumnType("bit");

                    b.Property<string>("Split")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eventi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbc4d833-dedb-46e0-97ec-0c7f8762126f"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 7, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vacanze"
                        },
                        new
                        {
                            Id = new Guid("30149fb0-e5cb-488f-843a-1e14e8e11eb8"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("c022be25-4a21-47dc-9494-edacdb10bdad"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("dc941a37-eb4b-4435-8485-4476652dd10e"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("765929b8-b37f-450b-a1b1-895ae26b9ed3"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("96a49e7d-92fa-4221-b9bb-f23ccbe5b366"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("4788e4b1-01ba-4445-bbd3-6f4e9589c756"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("81b4d0d2-8cbb-4ba4-bb1a-ef3aa7b94b3e"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("5b11ac79-e032-45aa-80cb-969ada2fad71"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("1cffbb60-452c-40ad-94da-ff8564cfbe05"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("1abbf3a3-62f4-472d-bdab-636c8ba06553"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("50efddd8-e3c5-4c3c-bb0d-df2a9d3a1c6c"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 14, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Week-end"
                        },
                        new
                        {
                            Id = new Guid("10f70e12-5ae5-47d3-ba20-e09f6824df33"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("8113fea2-ed4e-459c-bbe3-48b4358a3dea"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("3b0bea7e-24f5-42ea-8f33-3489140cb143"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("714927af-4103-4b2b-9117-b6fac960f3db"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 16, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("00a1f0d7-706e-463f-8223-8f8dca3abdee"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("8b0471f6-dd91-4dde-96d7-faa8abdda0e5"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("bf8eb095-b7c5-4e25-950f-4b03c4fcca89"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("592850bb-6cff-486d-ae89-d74b4e6902fa"),
                            AllDay = false,
                            Background = false,
                            Class = "straordinario",
                            Deletable = false,
                            End = new DateTime(2024, 1, 17, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 17, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Straordinario"
                        },
                        new
                        {
                            Id = new Guid("5d4732ff-4530-4b98-93d3-e309f4cb9436"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 21, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ferie"
                        },
                        new
                        {
                            Id = new Guid("3f2eed58-1a35-49d9-871c-343c680e692b"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("ac99fd17-c655-409d-9721-dcff48fef6cc"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("10257d78-d560-4701-9e9d-9ac707e70839"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ferie"
                        },
                        new
                        {
                            Id = new Guid("e191a1e6-a72a-4155-a66f-49f18558f076"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("b27b71af-c694-459e-a53d-1360383c9b5e"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("231a1d13-e539-4902-ab86-c80080a072ac"),
                            AllDay = false,
                            Background = false,
                            Class = "straordinario",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Straordinario"
                        },
                        new
                        {
                            Id = new Guid("5becb32b-accd-473d-8be7-201c4823a6b5"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("f830fc03-c805-46d1-b234-ecd0af5f6154"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("9173f3a6-56a5-4636-9305-4e5af3dd97c7"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 1, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("956dfb30-829a-435a-bba1-03d7dd68de3d"),
                            AllDay = false,
                            Background = false,
                            Class = "straordinario",
                            Deletable = false,
                            End = new DateTime(2024, 1, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Straordinario"
                        },
                        new
                        {
                            Id = new Guid("4870820b-2740-49ab-88cc-dddda258fd96"),
                            AllDay = true,
                            Background = true,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 2, 4, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Feria"
                        },
                        new
                        {
                            Id = new Guid("d978dab1-f896-4b3d-a562-0a77708b6259"),
                            AllDay = true,
                            Background = true,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 2, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("332b3702-b23c-4d1c-b7c4-fee6b82a22b9"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("bec85dbc-38de-4e1d-8f18-7b6dc2bff6b8"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 2, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("110996c4-e104-4b62-af8c-1bc94f2338f5"),
                            AllDay = true,
                            Background = true,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("c825a0c9-08b6-4feb-8355-85aa6e7cc870"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 2, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("d24db327-0080-4524-929a-d47fb13230c9"),
                            AllDay = true,
                            Background = true,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        });
                });

            modelBuilder.Entity("Core.Services.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3de6883f-9a0b-4667-aa53-0fbc52c4d300"),
                            Email = "email1@test.it",
                            FirstName = "Nome1",
                            LastName = "Cognome1",
                            NickName = "Nickname1",
                            Password = "M0Cuk9OsrcS/rTLGf5SY6DUPqU2rGc1wwV2IL88GVGo="
                        },
                        new
                        {
                            Id = new Guid("a030ee81-31c7-47d0-9309-408cb5ac0ac7"),
                            Email = "email2@test.it",
                            FirstName = "Nome2",
                            LastName = "Cognome2",
                            NickName = "Nickname2",
                            Password = "Uy6qvZV0iA2/drm4zACDLCCm7BE9aCKZVQ16bg80XiU="
                        },
                        new
                        {
                            Id = new Guid("bfdef48b-c7ea-4227-8333-c635af267354"),
                            Email = "email3@test.it",
                            FirstName = "Nome3",
                            LastName = "Cognome3",
                            NickName = "Nickname3",
                            Password = "Uy6qvZV0iA2/drm4zACDLCCm7BE9aCKZVQ16bg80XiU="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
