// <auto-generated />
using System;
using Core.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20240206191701_AddTablesAndModelSeedData")]
    partial class AddTablesAndModelSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Feria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ferie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c58ee64d-759a-4027-be0e-70f10f3d6864"),
                            DataFine = new DateTime(2024, 1, 7, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Vacanza",
                            Durata = 7
                        },
                        new
                        {
                            Id = new Guid("ba60bf9e-e974-4bdb-bf62-37495c967447"),
                            DataFine = new DateTime(2024, 1, 14, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Week-end",
                            Durata = 2
                        },
                        new
                        {
                            Id = new Guid("3da511ad-41de-4c7d-bc12-c212c9078c3c"),
                            DataFine = new DateTime(2024, 1, 21, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Ferie",
                            Durata = 4
                        },
                        new
                        {
                            Id = new Guid("cebda61f-07f6-4bd5-b373-48c99d694aa1"),
                            DataFine = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Ferie",
                            Durata = 60
                        },
                        new
                        {
                            Id = new Guid("f5d34b3c-6464-4cf9-9282-06b8f4955ee3"),
                            DataFine = new DateTime(2024, 2, 4, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Ferie",
                            Durata = 4
                        });
                });

            modelBuilder.Entity("Core.Models.NotteFuori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViaggio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NottiFuori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8aec9db-23f6-4ac6-835f-59cec3a26862"),
                            Commessa = "Commessa di notte fuori",
                            Data = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di notte fuori",
                            TipoViaggio = "Lavoro"
                        },
                        new
                        {
                            Id = new Guid("e826590d-467c-4ce8-b5d2-2ad369796c9a"),
                            Commessa = "Riparazione",
                            Data = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Data la distanza tra l'azienda e cliente necessita di essere vicini per velocizzare la riparazione per il giorno dopo",
                            TipoViaggio = "Lavoro"
                        });
                });

            modelBuilder.Entity("Core.Models.Permesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime2");

                    b.Property<int>("OreTotali")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permessi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f50602e4-3871-4239-b635-a5955ea26f75"),
                            Data = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Medica",
                            OraFine = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 120
                        },
                        new
                        {
                            Id = new Guid("fed7594f-3738-4cb5-bc0f-a459aa37e58b"),
                            Data = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di permesso",
                            OraFine = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 180
                        },
                        new
                        {
                            Id = new Guid("c855aa2a-26a4-4d70-8e7a-4a766b486aba"),
                            Data = new DateTime(2024, 1, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Familiare",
                            OraFine = new DateTime(2024, 1, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 180
                        },
                        new
                        {
                            Id = new Guid("5fc914a8-e7d9-471d-bb50-99dbc3b69bab"),
                            Data = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Malattia",
                            OraFine = new DateTime(2024, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 240
                        },
                        new
                        {
                            Id = new Guid("1b812db9-c22f-4959-ad71-95bbdfe13d6d"),
                            Data = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Malattia",
                            OraFine = new DateTime(2024, 2, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 180
                        },
                        new
                        {
                            Id = new Guid("ad585349-659f-4193-964c-7fb41c9f7ffd"),
                            Data = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Familiare",
                            OraFine = new DateTime(2024, 2, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 180
                        });
                });

            modelBuilder.Entity("Core.Models.Rendicontazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime2");

                    b.Property<int>("OreTotali")
                        .HasColumnType("int");

                    b.Property<bool>("Straordinario")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rendicontazioni");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee9be0b6-cf5f-4f0a-875c-81b160d296f4"),
                            Commessa = "Sistemazione",
                            Data = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Sistemato un problema del cliente",
                            OraFine = new DateTime(2024, 1, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("1991f4fc-4a08-482d-b2f4-fa46c67250e6"),
                            Commessa = "Sistemazione",
                            Data = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Sistemato un problema del cliente",
                            OraFine = new DateTime(2024, 1, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("822ae6e2-5bbf-47b6-b165-6aa432dc5e41"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto",
                            OraFine = new DateTime(2024, 1, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("918c0549-4f33-42a7-9e43-bc01200a2296"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto",
                            OraFine = new DateTime(2024, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("e6080929-6b69-4e8f-9385-306a63de6e91"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("99e58bad-c654-4c0d-b5a5-7703c69bf98b"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro per un progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("66e679b9-c84b-4621-aada-461bc5931786"),
                            Commessa = "progetto",
                            Data = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Elaborazione del progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("6edb5652-ebc2-4f26-b7d4-80dc23ba3b04"),
                            Commessa = "progetto",
                            Data = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Elaborazione del progetto di gruppo",
                            OraFine = new DateTime(2024, 1, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("ef07bbe1-d7a2-437a-a6a4-253e3714e394"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("65fa6ad2-9b89-47d8-bce6-dab654bec07a"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("7c2446a2-db04-4ae0-a082-ee3fa21b2817"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Pianificazione del progetto",
                            OraFine = new DateTime(2024, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("89be85f1-df28-4e6f-81a4-55d1ce1b4e74"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Pianificazione del progetto",
                            OraFine = new DateTime(2024, 1, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 3,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("ba04406d-38f0-47c8-89c1-c538da1a7816"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("872004bc-fd9e-44e2-a3d5-5b3a9e89d926"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("c22fded0-c7f9-4cb0-a5ee-6fe529843eff"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 17, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 17, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 17, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 1,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("eaf62043-d309-4575-bab2-d434cde2d21b"),
                            Commessa = "Commessa di rendicontazione",
                            Data = new DateTime(2024, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Rendicontazioni",
                            OraFine = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 2,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("c97faa20-ba64-4a05-8736-650c786461f5"),
                            Commessa = "Commessa di rendicontazione",
                            Data = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Rendicontazioni",
                            OraFine = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 1,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("099c45c2-a0f3-440f-af72-c0db91721199"),
                            Commessa = "Commessa di rendicontazione",
                            Data = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Rendicontazioni",
                            OraFine = new DateTime(2024, 1, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 2,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("71a64413-52af-4008-bf9d-afed4288a177"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 1, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 3,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("44aabf16-1106-44d6-85ff-e2efe15c1a6c"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 1, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro del progetto straordinario",
                            OraFine = new DateTime(2024, 1, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 1, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 3,
                            Straordinario = true
                        },
                        new
                        {
                            Id = new Guid("154d54eb-06cd-42ed-a54b-0495b4b08859"),
                            Commessa = "Aggiustamento",
                            Data = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Aggiustamento ad un problema del cliente",
                            OraFine = new DateTime(2024, 2, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("affa3b81-ffc3-4e68-b379-4e06d69678ec"),
                            Commessa = "Progetto",
                            Data = new DateTime(2024, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Termine del progetto",
                            OraFine = new DateTime(2024, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        },
                        new
                        {
                            Id = new Guid("14debad8-ec53-4bcd-8be4-2c15f8d8d538"),
                            Commessa = "Lavoro",
                            Data = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Lavoro",
                            OraFine = new DateTime(2024, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OraInizio = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OreTotali = 4,
                            Straordinario = false
                        });
                });

            modelBuilder.Entity("Core.Models.Rimborso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CartaAziendale")
                        .HasColumnType("bit");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rimborsi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e92a3649-ec84-4d1c-a0a2-c9053d2db8f5"),
                            CartaAziendale = false,
                            Commessa = "Commessa di rimborso",
                            Data = new DateTime(2024, 1, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Rimborso per il viaggio",
                            Importo = 100
                        },
                        new
                        {
                            Id = new Guid("b5a65c24-ab43-44bc-a296-244b525b5d32"),
                            CartaAziendale = false,
                            Commessa = "Commessa di rimborso",
                            Data = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di rimborso",
                            Importo = 100
                        },
                        new
                        {
                            Id = new Guid("46909b40-6e92-42e8-b120-d1657f9e9c40"),
                            CartaAziendale = true,
                            Commessa = "Riparazione",
                            Data = new DateTime(2024, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Rimborso per il viaggio",
                            Importo = 120
                        });
                });

            modelBuilder.Entity("Core.Models.Trasferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoAziendale")
                        .HasColumnType("bit");

                    b.Property<int>("Chilometri")
                        .HasColumnType("int");

                    b.Property<string>("Commessa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trasferte");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98986b72-f25c-43b7-af3f-bb41244195e2"),
                            AutoAziendale = false,
                            Chilometri = 200,
                            Commessa = "Aggiornamento",
                            DataFine = new DateTime(2024, 1, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 16, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Aggiornamento del sistema richiesto al cliente"
                        },
                        new
                        {
                            Id = new Guid("c04c737a-2032-4680-ae6f-7072fe060085"),
                            AutoAziendale = false,
                            Chilometri = 200,
                            Commessa = "Commessa di Trasferte",
                            DataFine = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Dettagli di Trasferte"
                        },
                        new
                        {
                            Id = new Guid("8b72b6dd-3ed4-4f6e-bd6d-fc1d45da791f"),
                            AutoAziendale = true,
                            Chilometri = 350,
                            Commessa = "Riparazione",
                            DataFine = new DateTime(2024, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInizio = new DateTime(2024, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Dettagli = "Riparazione ad un guasto ad un macchinario del cliente"
                        });
                });

            modelBuilder.Entity("Core.Models.VueCalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AllDay")
                        .HasColumnType("bit");

                    b.Property<bool?>("Background")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Resizable")
                        .HasColumnType("bit");

                    b.Property<string>("Split")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eventi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98ba4c76-a205-45d5-965d-1e214d785d84"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 7, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vacanze"
                        },
                        new
                        {
                            Id = new Guid("6ac20d92-6050-46b9-b62a-f845c8690f5e"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("fdc86433-6a79-461c-951a-d8f80e0d0e17"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("c292fb4a-2102-478f-b98d-2b695d597335"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("0e26aa2f-9162-4947-a7ba-f4ee9b634a24"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("a35c1a6b-e7dc-4183-baf0-9951d1503007"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("1bada44d-bc5a-4c0a-babd-be4336abd201"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("3904c044-b8d1-407a-b408-ef4205a1117f"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("7c738465-495d-4770-97ce-0023e5da9aa2"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("a3b660d1-461a-4b25-af8e-73592d0da99f"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("5ff5678b-9c07-4775-a8c9-28f12249faa3"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("f4df6b14-3208-4b4b-ab01-1f7d80c50494"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 14, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Week-end"
                        },
                        new
                        {
                            Id = new Guid("6fcba647-9774-45d1-b9ea-c8d33c3e346a"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("7f400b10-c82c-42be-91ba-057f91c7250d"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("2d4e87c0-47fe-45c3-8ebd-90818506738f"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("13327f06-fc7a-4b01-b997-73be8d27b751"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 16, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("8a84e9ce-dfca-4911-af3d-24b3c5671eed"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("4142060c-cb96-4797-a528-d5ada3648a22"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("5bca2818-3f30-4c96-9b38-cdcdd6eef3c1"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("4453240c-198c-404d-bbb3-aa272115e2cc"),
                            AllDay = false,
                            Background = false,
                            Class = "straordinario",
                            Deletable = false,
                            End = new DateTime(2024, 1, 17, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 17, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Straordinario"
                        },
                        new
                        {
                            Id = new Guid("8e06062f-8ecb-460a-98e6-7018cc4b0f68"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 21, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ferie"
                        },
                        new
                        {
                            Id = new Guid("055263b8-2133-4e5b-b740-eea0e23becff"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("3737ad68-5f67-4aaa-89e4-adbd072e59af"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("a596ffaa-0eae-4aee-b178-b0b20e57d38e"),
                            AllDay = false,
                            Background = false,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ferie"
                        },
                        new
                        {
                            Id = new Guid("bc87e827-241d-47bf-a02e-5b386a990d33"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("6b12f417-224f-4964-b704-2f5014c59297"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("692d6168-5603-4ed7-9a10-8cd252d4750e"),
                            AllDay = false,
                            Background = false,
                            Class = "straordinario",
                            Deletable = false,
                            End = new DateTime(2024, 1, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Straordinario"
                        },
                        new
                        {
                            Id = new Guid("1f04628f-a7cd-4407-abe9-c5fb429f0e18"),
                            AllDay = false,
                            Background = false,
                            Class = "trasferta",
                            Deletable = false,
                            End = new DateTime(2024, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Trasferta"
                        },
                        new
                        {
                            Id = new Guid("a95c5aa3-71ee-44a2-ac97-f3961ecf1727"),
                            AllDay = false,
                            Background = false,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 1, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("52183a19-2f8c-4d62-8028-ae307fbe1665"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 1, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("d14ea151-bb36-481c-989a-ed73700b0213"),
                            AllDay = false,
                            Background = false,
                            Class = "straordinario",
                            Deletable = false,
                            End = new DateTime(2024, 1, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 1, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Straordinario"
                        },
                        new
                        {
                            Id = new Guid("91341ec9-f97a-44aa-812d-693eb05a9dbe"),
                            AllDay = true,
                            Background = true,
                            Class = "libero",
                            Deletable = false,
                            End = new DateTime(2024, 2, 4, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Feria"
                        },
                        new
                        {
                            Id = new Guid("e919393d-40a1-4ce1-b9b4-e336fcc6284d"),
                            AllDay = true,
                            Background = true,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 2, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("1fd64cb4-a2d8-4b05-9652-33e2a35af577"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("d8ff3076-cfb9-4d7b-a90e-c4ffcaf8fdf2"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 2, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("df94b160-4e26-4eba-b039-ee2df5e851a9"),
                            AllDay = true,
                            Background = true,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        },
                        new
                        {
                            Id = new Guid("0bd563b3-d951-4437-8e5e-82f8858314a9"),
                            AllDay = false,
                            Background = false,
                            Class = "permesso",
                            Deletable = false,
                            End = new DateTime(2024, 2, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Permesso"
                        },
                        new
                        {
                            Id = new Guid("506bcd84-c88d-41ef-8bed-efab58a1b93b"),
                            AllDay = true,
                            Background = true,
                            Class = "rendicontazione",
                            Deletable = false,
                            End = new DateTime(2024, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Resizable = false,
                            Split = "",
                            Start = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rendicontazione"
                        });
                });

            modelBuilder.Entity("Core.Services.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3de6883f-9a0b-4667-aa53-0fbc52c4d300"),
                            Email = "email1@test.it",
                            FirstName = "Nome1",
                            LastName = "Cognome1",
                            NickName = "Nickname1",
                            Password = "M0Cuk9OsrcS/rTLGf5SY6DUPqU2rGc1wwV2IL88GVGo="
                        },
                        new
                        {
                            Id = new Guid("a030ee81-31c7-47d0-9309-408cb5ac0ac7"),
                            Email = "email2@test.it",
                            FirstName = "Nome2",
                            LastName = "Cognome2",
                            NickName = "Nickname2",
                            Password = "Uy6qvZV0iA2/drm4zACDLCCm7BE9aCKZVQ16bg80XiU="
                        },
                        new
                        {
                            Id = new Guid("bfdef48b-c7ea-4227-8333-c635af267354"),
                            Email = "email3@test.it",
                            FirstName = "Nome3",
                            LastName = "Cognome3",
                            NickName = "Nickname3",
                            Password = "Uy6qvZV0iA2/drm4zACDLCCm7BE9aCKZVQ16bg80XiU="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
